### ISSUE TITLE
Is everything still under development?

### ISSUE THREAD

**Issue by developer-ken** [ProtocolSupport/ProtocolSupportPocketIssues#113]
I wonder if this project (for MCPE) is still under development or just being deprecated?
This project had really helped me a lot (even without mcpe support). I wonder if I would be able to see any working version with mcpe support in the future.
Thanks.

**Comment by Shevchik** [comment]
Project is still active, just under private development for now. Watch the ProtocolSupport MCPE support issue, as long as it is still open, mcpe support is still in plans.

**Comment by magicus** [comment]
@Shevchik I did not think the AGPL license allowed private development. Or rather, private development that is being deployed.

**Comment by Shevchik** [comment]
It doesn't. But since i'm the author of most of the code (literally 99%, only a few lines of main PS branch were from contributors), i still retain full rights for it. Since PE branch is written from scratch to fix wrong design decisions and wrong packet formats, no code from old mcpe is used (and that's where most outside contributions were). Mineteria branch is also quite different to master PS branch, because it runs on heavily modified 1.12.2, so i had to write all the code again for that.
So that private development mcpe branch is more like a copy-paste from Mineteria pe branch adapted to latest version (which also means that it doesn't have all the 1.16.4 features). After solving some other design problems of main PS branch (for example NetworkDataCache being a big bloat of every type of cached data regardless of version, or NetworkItemStack doing remap being a single step. instead of modern -> legacy -> version format) i am planning to release what i already have, but before that it ain't happening, otherwise it will end up like it ended last 4 attempts at making pocket edition support (scrapped because of internal design problems making code a bunch of crutches on top of crutches held together by duct tape).
