### ISSUE TITLE
[PSB] PE players have the wrong IP when using IP Forward with PSBungee

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportPocketIssues#51]
Basically, when using PSPE with PSB the backend server gets the Bungee IP, which can make plugins do weird things.

IMO it should be marked as HIGH priority.

**Comment by MrPowerGamerBR** [comment]
Update: IP forwarding does work fine, the issue only happens if the BungeeCord server is behind NAT.

When the Bungee server is behind NAT, BungeeCord uses the local IP as the player's IP.

I *guess* this also affects ProtocolSupportPE itself, so I think the issue lies somewhere else not in PSPE or PSBungee.

![https://i.imgur.com/Y2jqOW9.png](https://i.imgur.com/Y2jqOW9.png)
![https://i.imgur.com/ZCSgkvT.png](https://i.imgur.com/ZCSgkvT.png)

**Comment by Artuto** [comment]
Fixed in my PSB PR.
